# Frontend
FROM node:20-alpine

WORKDIR /app

COPY frontend/package.json .

RUN npm cache clean --force
RUN npm install

COPY frontend/ .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "7777"]
