# Backend Dev Dockerfile (Go/Gin)

FROM golang:1.25-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 6767

CMD ["go", "run", "./cmd/server"]
# Note: app should listen on port 6767
