# Backend Dev Dockerfile (Go/Gin)

FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 6767

CMD ["air", "-c", ".air.toml"]
# Note: app should listen on port 6767
